### PR TITLE
bootloader: Windows: fix behavior when runtime tmpdir is a drive letter

### LINKED ISSUE #6051: runtime_tmpdir set to drive name causes unexpected behavior
## Description of the issue
Using the flag runtime_tmpdir and setting it to
`runtime_tmpdir='C:'`
will cause unxpected behaviors. If the executable that is created is ran from the C: drive, the temporary directory created will be in the same path as the executable. However, if the executable that is created is ran from a different drive (i.e. E:), then the temporary folder gets created in `C:\`.
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.2```
* Version of Python: 
* Platform: 
* How you installed Python: 
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

### PR DESCRIPTION
**Pull request by rokm**
Fix extraction behavior of Windows `onefile` builds when the run-time temporary directory (`--runtime-tmpdir`) is set to just a drive letter (e.g., `"c:"`), either directly or via an expanded environment variable, such as `%HOMEDRIVE%`.

In such cases, we must avoid calling `_wfullpath`, because as per its docs, "If the relPath argument specifies a disk drive, the
current directory of this drive is combined with the path". Instead, we should treat such paths separately, so that the final temporary directory is created in the drive's root (e.g., `"c:\_MEIXXXXX"`).

Fixes #6051.

### CODE REVIEW

File: bootloader/src/pyi_win32_utils.c [hunk 1]
```diff
@@ -491,5 +491,34 @@ int pyi_win32_is_symlink(const wchar_t *path)
...
+        /* First character must be a letter */
+        if (!iswalpha(path[0])) {
+            return 0;
+        }
+        /* Second character must be the colon */
+        if (path[1] != L':') {
+            return 0;
+        }
+        /* Third character, if present, must be the Windows directory separator */
+        if (len > 2 && (path[2] != L'\\')) {
```
Comment (bwoodsend) [inline bootloader/src/pyi_win32_utils.c:513]: Could `path[2]` not also be `'/'`?

Comment (rokm) [reply bootloader/src/pyi_win32_utils.c:513]: It *shouldn't* be, because our Windows-specific bootloader codepaths assume Windows separators (e.g., [here](https://github.com/pyinstaller/pyinstaller/blob/1cadf324421d32759b205d14087391f90d6ef8ae/bootloader/src/pyi_utils.c#L277)). But with the world we live in, it *could* well be, although it takes some effort to set up such scenario - for example, if the path (`c:/`) is stored to environment variable, and the environment variable is passed as `runtime_tmpdir` via spec file. 

If it were passed directly on command-line, it would end up expanded, and then TOC would normalize it:
https://github.com/pyinstaller/pyinstaller/blob/1cadf324421d32759b205d14087391f90d6ef8ae/PyInstaller/archive/writers.py#L262-L268

(As a side note, the `nm` passed to the `normpath` is actually not just the path, but whole run-time option, e.g., `'pyi-runtime-tmpdir c:/'`. So `normpath` seems to end up stripping the trailing separator, even though it otherwise would not.)

But, it looks like that even if you manage to smuggle a `c:/` in and we don't treat it as a drive root because of separator mismatch, that `_wfullpath` call changes it from `c:/` to `c:\` and all is well. So I'd prefer to keep it this way rather than treat `c:/` as drive root and then have to deal with unexpected separator somewhere else...

**Review by bwoodsend — APPROVED** [review]
